name: glf
version: 0.2.0
author: david bernard <david.bernard.31@gmail.com>
description: another toolbox for webgl (used by vdrones)
homepage: http://github.com/davidB/glf
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  vector_math: '>=1.3.5'
dev_dependencies:
  asset_pack: '>=0.6.2'
  js: '>=0.2.0 <0.3.0'
  unittest: '>=0.8.10+3 <0.9.0'
