name: glf
version: 0.1.0
author: David Bernard
description: another toolbox for webgl
homepage: http://github.com/davidB/glf
dependencies:
  browser: any
  vector_math: '>=1.3.0'
dev_dependencies:
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
